#server port configuration
server:
  port: 9096

#application name configuration
spring:
  application:
    name: RENT-HUB-GATEWAY
  profiles:
    active: local

  cloud:
    gateway:
      routes:

#********** AUTH-SERVICE rounting **************#
        - id: AUTH-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/rent-hub/api/v1/v2/auth/**
          filters:
            - AuthenticationFilter

#********** TENANTS-SERVICE rounting **************#
        - id: TENANTS-SERVICE
          uri: http://localhost:9098
          predicates:
            - Path=/rent-hub/api/v1/tenants/**
          filters:
            - AuthenticationFilter

#********** PROPERTY-SERVICE rounting **************#
        - id: PROPERTY-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/rent-hub/api/v1/properties/**
          filters:
            - AuthenticationFilter

#********** AGREEMENT-SERVICE rounting **************#
        - id: AGREEMENT-SERVICE
          uri: http://localhost:9099
          predicates:
            - Path=/rent-hub/api/v1/agreement/**
          filters:
            - AuthenticationFilter

#********** PAYMENT-SERVICE rounting **************#
        - id: PAYMENT-SERVICE
          uri: http://localhost:9097
          predicates:
            - Path=/rent-hub/api/v1/payment/**
          filters:
            - AuthenticationFilter

#********** NOTIFICATION-SERVICE rounting **************#
        - id: NOTIFICATION-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/rent-hub/api/v1/notifications/**
          filters:
            - AuthenticationFilter


        - id: PROPERTY-IMAGES
          uri: http://localhost:9090
          predicates:
            - Path=/uploads/properties/**

        - id: NOTIFICATION-WS
          uri: ws://localhost:9092
          predicates:
            - Path=/rent-hub/ws/**
          filters:
            - StripPrefix=1

        - id: WEB-BFF
          uri: http://localhost:9095
          predicates:
            - Path=/rent-hub/api/v1/**
          filters:
            - AuthenticationFilter

#health configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


# ==========================================================
# JWT CONFIGURATION:JWT secret key (from environment variable)
# ==========================================================
jwt:
  secret: ${JWT_SECRET}


# ==========================================================
# CORS CONFIGURATION : Comma-separated allowed origins (from env variable)
# ==========================================================
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

# ================================
# LOGGING
# ================================
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) [request-id=%X{requestId}] [trace-id=%X{trace_id}] [%X{clientIp}] %clr([%thread]){magenta} %clr(%logger{36}){cyan} : %msg%n%wEx{5}"
  level:
    root: INFO
    org.hibernate.orm.connections.pooling: ERROR
    com.vikas.webbff: DEBUG
