server:
  port: ${PORT:8080}

spring:
  application:
    name: RENT-HUB-GATEWAY

  cloud:
    gateway:
      routes:

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/rent-hub/auth/**
          filters:
            - AuthenticationFilter

        - id: WEB-BFF
          uri: lb://WEB-BFF
          predicates:
            - Path=/rent-hub/api/v1/**
          filters:
            - AuthenticationFilter

        - id: PROPERTY-IMAGES
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/uploads/properties/**

        - id: NOTIFICATION-WS
          uri: lb:ws://NOTIFICATION-SERVICE
          predicates:
            - Path=/rent-hub/ws/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: https://eureca-server-e09m.onrender.com/eureka

  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always